"""Generate publication-ready figures (PDF+PNG) for the AAMAS paper from final results.

Run from the repository root: .venv/Scripts/python.exe scripts/generate_paper_assets.py
Outputs to paper_notes/paper_assets/figures/. LaTeX tables live alongside in
paper_notes/paper_assets/tables/ (hand-authored, not regenerated by this script).

fig1 is computed from the pre-registered 10-draw random baselines; fig2 uses hardcoded numbers
from the final team-level robustness table; fig3 and fig4 are recomputed from artifacts/.
"""
import glob
import json
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D

PROJECT = Path(__file__).resolve().parents[1]
FIG_DIR = PROJECT / "paper_notes" / "paper_assets" / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "font.family": "serif",
    "font.size": 8,
    "axes.titlesize": 8,
    "axes.labelsize": 8,
    "legend.fontsize": 7,
    "xtick.labelsize": 7,
    "ytick.labelsize": 7,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "grid.linewidth": 0.5,
    "figure.dpi": 150,
})


def save(fig, name):
    fig.savefig(FIG_DIR / f"{name}.pdf", bbox_inches="tight")
    fig.savefig(FIG_DIR / f"{name}.png", bbox_inches="tight")
    plt.close(fig)
    print(f"saved {name}.pdf / .png")


def fig1_claim1():
    colors = {
        "Qwen3-0.6B, arith.": "#1b6ca8",
        "SmolLM2-1.7B, arith.": "#2e9e5b",
        "SmolLM2, bAbI 2-stage": "#c9622d",
        "SmolLM2, bAbI 4-stage": "#8a3ea8",
    }
    # Computed from the pre-registered 10-draw random baselines (bars: shared random mask,
    # diamonds: independent random masks), two-level bootstrap CIs for the bars.
    import sys
    sys.path.insert(0, str(PROJECT / "scripts"))
    import analyze_random_baseline as A
    import generate_paper_tables as G
    short = dict(zip([label for label, _ in G.SETTINGS], colors))
    claim1, indep = {}, {}
    for label, cells in G.SETTINGS:
        for (sp, names), stem in zip(cells.items(), G.INDEP_STEMS[label]):
            _, role, shared, ind = A.draws(names, stem)
            key = int(sp.split("\\")[0])
            claim1.setdefault(short[label], {})[key] = A.two_level(role, shared)
            indep.setdefault(short[label], {})[key] = float(role.mean() - ind.mean())
    # one ACM column is ~3.33 in wide; drawing at that size keeps fonts readable without scaling
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    settings = list(colors)
    sparsities = [5, 10, 15]
    bar_width = 0.19
    x = np.arange(len(sparsities))
    for i, setting in enumerate(settings):
        diffs = [claim1[setting][sp][0] for sp in sparsities]
        lows = [claim1[setting][sp][0] - claim1[setting][sp][1] for sp in sparsities]
        highs = [claim1[setting][sp][2] - claim1[setting][sp][0] for sp in sparsities]
        offset = (i - (len(settings) - 1) / 2) * bar_width
        ax.bar(x + offset, diffs, bar_width, label=setting, color=colors[setting],
               yerr=[lows, highs], capsize=1.5, error_kw={"linewidth": 0.6, "ecolor": "#333333"})
        ax.scatter(x + offset, [indep[setting][sp] for sp in sparsities], marker="D", s=9,
                   color="white", edgecolor="black", linewidth=0.6, zorder=3)
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(["5%", "10%", "15%"])
    ax.set_xlabel("Sparsity")
    ax.set_ylabel("Role $-$ random\n(team accuracy)")
    ax.set_ylim(-0.25, 1.0)
    handles, labels = ax.get_legend_handles_labels()
    handles.append(Line2D([], [], marker="D", linestyle="", markersize=3.5, markerfacecolor="white",
                          markeredgecolor="black", markeredgewidth=0.6))
    labels.append("Independent random masks")
    ax.legend(handles, labels, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=2, frameon=False,
              columnspacing=0.8, handlelength=1.0, handletextpad=0.4)
    fig.tight_layout()
    save(fig, "fig1_claim1_role_vs_random")


def fig2_compensation():
    compensation = [
        ("Original draw, 5%", -0.1875, -0.3333, -0.0417),
        ("Original draw, 10%", -0.1042, -0.2708, 0.0625),
        ("Original draw, 15%", 0.0208, -0.1250, 0.1667),
        ("Seed 101, 5%", 0.0625, -0.0625, 0.1875),
        ("Seed 101, 10%", 0.0417, -0.1042, 0.1875),
        ("Seed 101, 15%", -0.0208, -0.1667, 0.1250),
        ("Seed 202, 5%", -0.1458, -0.2917, 0.0000),
        ("Seed 202, 10%", 0.0417, -0.0833, 0.1667),
        ("Seed 202, 15%", -0.0417, -0.1875, 0.1042),
        ("Seed 303, 5%", 0.0000, -0.1458, 0.1458),
        ("Seed 303, 10%", 0.0417, -0.0833, 0.1667),
        ("Seed 303, 15%", 0.0000, -0.1458, 0.1458),
    ]
    fig, ax = plt.subplots(figsize=(3.4, 3.2))
    ys = np.arange(len(compensation))[::-1]
    for y, (label, d, lo, hi) in zip(ys, compensation):
        significant = lo > 0 or hi < 0
        color = "#c0392b" if significant else "#2e9e5b"
        ax.plot([lo, hi], [y, y], color=color, linewidth=1.3, solid_capstyle="round")
        ax.plot(d, y, "o", color=color, markersize=3)
    ax.axvline(0, color="black", linewidth=0.8, linestyle="--")
    ax.set_yticks(ys)
    ax.set_yticklabels([c[0] for c in compensation])
    ax.set_ylim(-0.6, len(compensation) - 0.4)
    ax.set_xlabel("Role $-$ unmasked (team accuracy, 95% CI)")
    legend_elems = [
        Line2D([0], [0], color="#2e9e5b", marker="o", label="Tied with unmasked"),
        Line2D([0], [0], color="#c0392b", marker="o", label="Significantly different"),
    ]
    ax.legend(handles=legend_elems, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=2, frameon=False,
              handlelength=1.2)
    fig.tight_layout()
    save(fig, "fig2_claim2_compensation_forest")


def _pruned_sets(mask):
    out = []
    for layer_idx in sorted(mask["layers"].keys(), key=int):
        layer = mask["layers"][layer_idx]
        width = layer["width"]
        selected = set(layer["selected_indices"])
        out.append(set(range(width)) - selected)
    return out


def _jaccard_matrix(mask_path):
    with open(mask_path, encoding="utf-8") as f:
        masks = json.load(f)
    roles = ["planner", "solver", "critic", "verifier"]
    pruned = {r: _pruned_sets(masks[r]) for r in roles}
    mat = np.zeros((4, 4))
    for i, r1 in enumerate(roles):
        for j, r2 in enumerate(roles):
            if i == j:
                mat[i, j] = 1.0
                continue
            vals = [len(a & b) / len(a | b) for a, b in zip(pruned[r1], pruned[r2]) if a or b]
            mat[i, j] = sum(vals) / len(vals)
    return roles, mat


def fig3_mask_overlap():
    fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.2))
    checkpoints = [
        ("Qwen-arithmetic", PROJECT / "artifacts/masks/aamas_controlled_confirmatory_s005_0.05.json"),
        ("SmolLM2-arithmetic", PROJECT / "artifacts/masks/aamas_smollm2_team_s005_0.05.json"),
        ("bAbI (SmolLM2)", PROJECT / "artifacts/masks/babi_pilot_s005_0.05.json"),
    ]
    im = None
    for ax, (label, path) in zip(axes, checkpoints):
        roles, mat = _jaccard_matrix(path)
        im = ax.imshow(mat, vmin=0, vmax=1, cmap="YlOrRd")
        ax.set_xticks(range(4))
        ax.set_yticks(range(4))
        ax.set_xticklabels([r[:4] for r in roles], rotation=45, ha="right")
        ax.set_yticklabels([r[:4] for r in roles])
        ax.set_title(label, fontsize=9)
        ax.grid(False)
        for i in range(4):
            for j in range(4):
                v = mat[i, j]
                ax.text(j, i, f"{v:.2f}", ha="center", va="center", fontsize=7.5,
                        color="white" if v > 0.55 else "black")
    fig.colorbar(im, ax=axes, shrink=0.8, label="Pruned-unit Jaccard overlap", pad=0.02)
    save(fig, "fig3_mask_overlap_heatmap")


def _analyze_stats(f):
    with open(f, encoding="utf-8") as fh:
        stats = json.load(fh)
    if stats.get("metadata", {}).get("backend") != "hf" or "solver" not in stats.get("mean_abs", {}):
        return None
    # persona-probe statistics use a different prompt condition; the diagnostic covers main runs only
    if stats["metadata"].get("include_system_prompt"):
        return None
    vals = [v for layer in stats["mean_abs"]["solver"] for v in layer]
    n = len(vals)
    mean = sum(vals) / n
    std = (sum((v - mean) ** 2 for v in vals) / n) ** 0.5
    cv = std / mean if mean else float("nan")
    total = sum(vals)
    probs = [v / total for v in vals if v > 0]
    entropy = -sum(p * math.log(p) for p in probs)
    return dict(model=stats["metadata"].get("model_id", "?"), cv=cv, norm_entropy=entropy / math.log(n))


def fig4_entropy_diagnostic():
    model_labels = {
        "Qwen/Qwen3-0.6B": "Qwen3-0.6B (FP16)",
        "HuggingFaceTB/SmolLM2-1.7B-Instruct": "SmolLM2-1.7B (int8)",
        "Qwen/Qwen2.5-3B-Instruct": "Qwen2.5-3B (int4)",
    }
    model_colors = {
        "Qwen/Qwen3-0.6B": "#1b6ca8",
        "HuggingFaceTB/SmolLM2-1.7B-Instruct": "#2e9e5b",
        "Qwen/Qwen2.5-3B-Instruct": "#c0392b",
    }
    points = []
    for f in sorted(glob.glob(str(PROJECT / "artifacts/activation_stats/*_stats.json"))):
        if f.endswith(".summary.json"):
            continue
        r = _analyze_stats(f)
        if r and r["model"] in model_labels:
            points.append(r)
    fig, ax = plt.subplots(figsize=(3.4, 2.8))
    seen = set()
    for p in points:
        label = model_labels[p["model"]] if p["model"] not in seen else None
        seen.add(p["model"])
        ax.scatter(p["cv"], p["norm_entropy"], color=model_colors[p["model"]], s=45,
                   edgecolor="white", linewidth=0.5, label=label, zorder=3)
    ax.set_xlabel("Coefficient of variation (CV)")
    ax.set_ylabel("Normalized Shannon entropy")
    ax.legend(loc="lower left", frameon=False)
    fig.tight_layout()
    save(fig, "fig4_entropy_diagnostic")


if __name__ == "__main__":
    fig1_claim1()
    fig2_compensation()
    fig3_mask_overlap()
    fig4_entropy_diagnostic()
    print("\nAll figures generated in", FIG_DIR)
